platform :ios, '10.0'

target 'skolera' do
  use_frameworks!
  
 #for loading screens
  pod 'SVProgressHUD'
  #for calling apis
  pod 'Alamofire', '4.9.1'
  #scroll view to allow keyboard to appear correctly
  pod 'TPKeyboardAvoiding'
  #download and cache images
  pod 'Kingfisher'
  #saving key/value info like access token to the keychain
  pod 'KeychainSwift'
  #Custom Progress Bar
  pod 'YLProgressBar'
  #Calendar View For Attendance Screen
  pod 'JTAppleCalendar', '7.1.6'
  #Timetable
  pod 'CalendarKit', '0.3.1'
  #Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  # Pods for PodTest
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.14.0'
  #Chat
  pod 'Chatto', '= 3.3.1'
  pod 'ChattoAdditions', '= 3.3.1'
  pod 'AlamofireImage'
  #Device type
  pod 'Device.swift'
  #Check updats
  pod 'NRAppUpdate'
  #Open images
  pod 'Lightbox'
  #IQKeyboard Manager
  pod 'IQKeyboardManager'
  #textView with placeholder
  pod 'KMPlaceholderTextView', '~> 1.4.0'
  #NVActivity loader
  pod 'NVActivityIndicatorView'
  #RichText
  pod 'RichTextView'
  pod 'SwiftDate', '~> 5.0'
  pod 'Lightbox'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'CVCalendar', '~> 1.6.2'
  pod "SkeletonView"
  pod 'IQKeyboardManagerSwift'
  #Image picker for chat
  pod 'TLPhotoPicker'
  #Reverse table view
  pod 'ReverseExtension'
end
